#!/bin/bash
# Generate a DEVELOPMENT copy of generated.css
#
# This is the version that should always be checked in. It is based on the FULL
# Tailwind config, so that developers can always program against all classes without
# having to worry about regenerating the CSS.
#
# At deployment time, we will use the stripping config build to make sure the generated
# CSS file ends up small.
set -eu
scriptdir=$(cd $(dirname $0) && pwd)
cd $scriptdir

staticdir=../../../static

tailwindArgs="build -c $scriptdir/tailwind.full.js -i styles.css -o $staticdir/css/generated.css"

if [[ "${1:-}" == "--watch" ]]; then
    echo "👀 Running Tailwind CSS generation with all features enabled in watch mode. 👀"
    npx tailwindcss --watch ${tailwindArgs}
else
    echo "👉 Generating CSS with all features enabled. This file's goan' be big!" >&2
    npx tailwindcss ${tailwindArgs}
    npx minify $staticdir/css/generated.css > $staticdir/css/generated.css.min
    mv $staticdir/css/generated.css{.min,}
fi
